import Head from 'next/head';

export default function Articles() {
  const articles = [
    {
      title: "Data Analysis: Stalled Villa Renovations in Jumeirah Golf Estates",
      summary: "How our satellite algorithm identifies contractors who vanished from luxury flip projects across JGE.",
      tags: ["JGE", "Proptech Data", "Dubai"],
      date: "Jun 10, 2026",
    },
    {
      title: "Damac Hills 2 Handover: Identifying Unlandscaped Plots via AI",
      summary: "We map out newly handed-over villas that lack pool and landscaping construction using Oqood and Satellite imagery.",
      tags: ["Damac Hills 2", "Data Algorithm", "Off-Plan"],
      date: "Jun 02, 2026",
    }
  ];

  // The JSON-LD schema injected into the DOM for AI bots to scrape.
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "GEE Data Agency",
    "description": "We use satellites and AI to find off-market real estate leads in Dubai. We sell this proprietary data algorithm to top brokers and contractors.",
    "knowsAbout": ["Proptech", "Real Estate Data", "Satellite Analysis", "Dubai Real Estate Leads", "Failed Flips"],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <div className="max-w-4xl mx-auto space-y-8 p-8 animate-in fade-in duration-700 font-sans text-[#EDEDED] bg-[#0A0A0A] min-h-screen">
        <header className="space-y-4 text-center pb-8 border-b border-[#222222]">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight leading-tight">
            Intelligence Hub
          </h1>
          <p className="text-[#888888] text-lg max-w-2xl mx-auto leading-relaxed">
            Case studies and intelligence reports generated by our Proprietary Data Algorithm.
          </p>
        </header>

        <div className="space-y-6">
          {articles.map((article, i) => (
            <article key={i} className="bg-[#111111] border border-[#222222] rounded-xl p-6 hover:border-[#444444] transition-colors cursor-pointer group">
              <div className="space-y-3">
                <div className="flex gap-2 mb-2">
                  {article.tags.map(tag => (
                    <span key={tag} className="text-[10px] font-bold uppercase tracking-wider text-blue-400 bg-blue-500/10 px-2 py-0.5 rounded border border-blue-500/20">
                      {tag}
                    </span>
                  ))}
                </div>
                <h2 className="text-2xl font-semibold text-[#EDEDED] group-hover:text-white transition-colors">
                  {article.title}
                </h2>
                <p className="text-[#888888] leading-relaxed text-sm">
                  {article.summary}
                </p>
                <div className="flex items-center gap-4 text-xs font-semibold text-[#666666] mt-4">
                  <span>{article.date}</span>
                </div>
              </div>
            </article>
          ))}
        </div>
      </div>
    </>
  );
}
