from sqlalchemy import Column, String, Integer, Float, ForeignKey, Boolean, DateTime
from sqlalchemy.orm import declarative_base, relationship
from datetime import datetime

Base = declarative_base()

class Lead(Base):
    """
    Core SQL Table representing a physical property identified by GEE.
    """
    __tablename__ = 'leads'

    id = Column(String, primary_key=True) # e.g. JUM1-COM-99
    lat = Column(Float, nullable=False)
    lng = Column(Float, nullable=False)
    
    gee_detection_date = Column(String)
    gee_description = Column(String)
    
    # Relationships
    transactions = relationship("Transaction", back_populates="lead", cascade="all, delete-orphan")
    commercial_license = relationship("CommercialLicense", back_populates="lead", uselist=False, cascade="all, delete-orphan")
    gemini_eval = relationship("GeminiEval", back_populates="lead", uselist=False, cascade="all, delete-orphan")

class Transaction(Base):
    """
    DLD Historical Transactions linked to a Lead.
    """
    __tablename__ = 'transactions'

    transaction_id = Column(String, primary_key=True)
    lead_id = Column(String, ForeignKey('leads.id'))
    
    date = Column(String)
    price_aed = Column(Float)
    price_per_sqft = Column(Float)
    property_type = Column(String)
    
    lead = relationship("Lead", back_populates="transactions")

class CommercialLicense(Base):
    """
    DED and Google Maps commercial data linked to a converted Lead.
    """
    __tablename__ = 'commercial_licenses'

    id = Column(Integer, primary_key=True, autoincrement=True)
    lead_id = Column(String, ForeignKey('leads.id'))
    
    ded_trade_name = Column(String)
    ded_activity = Column(String)
    ded_license_no = Column(String)
    
    gmaps_name = Column(String)
    gmaps_rating = Column(String)
    gmaps_url = Column(String)
    
    lead = relationship("Lead", back_populates="commercial_license")

class GeminiEval(Base):
    """
    The final QA report generated by the LLM Evaluator.
    """
    __tablename__ = 'gemini_evaluations'

    id = Column(Integer, primary_key=True, autoincrement=True)
    lead_id = Column(String, ForeignKey('leads.id'))
    
    is_usable = Column(Boolean, default=False)
    reliability_score = Column(Integer)
    reasoning = Column(String)
    
    lead = relationship("Lead", back_populates="gemini_eval")
